name: Release Tag

on:
  push:
    branches:
      - master
      - staging
      - qa


jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          release: minor
          tag_prefix: v