name: Release Tag

on:
  push:
    branches:
      - qa
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"


jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: v